
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_ldf_mode=deep
lib_deps =
    TFT_eSPI
    ; NimBLE-Arduino
    fbiego/ESP32Time@^2.0.4
    mathertel/RotaryEncoder@^1.5.3
lib_extra_dirs =
    /lib

board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
build_flags =
;   -D USE_NIMBLE
;   -D USER_SETUP_LOADED=1
;   -include .pio/libdeps/esp32-s3-devkitc-1/TFT_eSPI/User_Setups/Setup70b_ESP32_S3_ILI9341.h
 