"""
gen_version.py — PlatformIO pre-build script for controller firmware versioning.

Resolves the firmware version from (in priority order):
  1. GITHUB_REF_NAME env var (set by GitHub Actions on tag push).
     Expected form: ``controller-v<MAJOR>.<MINOR>.<PATCH>`` — the ``controller-v``
     prefix is stripped before parsing.
  2. ``git describe --tags --match 'controller-v*' --dirty`` output.
     Parses ``controller-v<MAJOR>.<MINOR>.<PATCH>[-<BUILD>-g<SHA>][-dirty]``.
  3. Fallback: ``0.0.0-dev``.

Writes ``controller/src/version.h`` with the resolved values. The write is
idempotent — if the resulting content matches the existing file byte-for-byte,
the file is not touched (avoids spurious PlatformIO rebuilds).

Wired up via ``extra_scripts = pre:scripts/gen_version.py`` in platformio.ini.
"""

import os
import re
import subprocess
import sys
from pathlib import Path


def _resolve_project_dir():
    """Resolve controller/ root regardless of how the script is invoked.

    PlatformIO ``exec()``s extra_scripts via SCons, so ``__file__`` is not
    defined. Prefer SCons ``env.subst("$PROJECT_DIR")``; fall back to argv[0]
    when running standalone.
    """
    try:  # pragma: no cover — PlatformIO/SCons path
        Import("env")  # noqa: F821  (injected by SCons)
        return Path(env.subst("$PROJECT_DIR")).resolve()  # noqa: F821
    except NameError:
        pass

    # Standalone fallback: derive from argv[0] (or cwd as last resort).
    argv0 = sys.argv[0] if sys.argv and sys.argv[0] else ""
    if argv0:
        script_path = Path(argv0).resolve()
        # scripts/gen_version.py → parent.parent = controller/
        if script_path.parent.name == "scripts":
            return script_path.parent.parent
    return Path.cwd().resolve()


PROJECT_DIR = _resolve_project_dir()
SRC_DIR = PROJECT_DIR / "src"
VERSION_HEADER = SRC_DIR / "version.h"

TAG_PREFIX = "controller-v"
# controller-v1.2.3 or controller-v1.2.3-4-gabcdef0[-dirty]
DESCRIBE_RE = re.compile(
    r"^controller-v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)"
    r"(?:-(?P<build>\d+)-g(?P<sha>[0-9a-f]+))?"
    r"(?P<dirty>-dirty)?$"
)
# Plain tag form: controller-v1.2.3 (no build/sha suffix)
PLAIN_TAG_RE = re.compile(
    r"^controller-v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$"
)


def _run_git(args):
    """Run a git command from the project dir; return stdout (stripped) or None."""
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=str(PROJECT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            text=True,
        )
    except FileNotFoundError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _short_sha():
    sha = _run_git(["rev-parse", "--short", "HEAD"])
    return sha if sha else "0000000"


def resolve_version():
    """Return (major, minor, patch, build, version_string, git_sha)."""
    git_sha = _short_sha()

    # 1. CI: GITHUB_REF_NAME on tag push.
    ref_name = os.environ.get("GITHUB_REF_NAME", "").strip()
    if ref_name.startswith(TAG_PREFIX):
        m = PLAIN_TAG_RE.match(ref_name)
        if m:
            major = int(m.group("major"))
            minor = int(m.group("minor"))
            patch = int(m.group("patch"))
            build = 0
            version_string = "{}.{}.{}".format(major, minor, patch)
            return major, minor, patch, build, version_string, git_sha

    # 2. git describe.
    describe = _run_git(
        ["describe", "--tags", "--match", "{}*".format(TAG_PREFIX), "--dirty"]
    )
    if describe:
        m = DESCRIBE_RE.match(describe)
        if m:
            major = int(m.group("major"))
            minor = int(m.group("minor"))
            patch = int(m.group("patch"))
            build = int(m.group("build")) if m.group("build") else 0
            sha = m.group("sha") or git_sha
            dirty_suffix = m.group("dirty") or ""
            if build > 0:
                version_string = "{}.{}.{}-{}-g{}{}".format(
                    major, minor, patch, build, sha, dirty_suffix
                )
            else:
                version_string = "{}.{}.{}{}".format(major, minor, patch, dirty_suffix)
            return major, minor, patch, build, version_string, sha

    # 3. Fallback.
    return 0, 0, 0, 0, "0.0.0-dev", git_sha


def render_header(major, minor, patch, build, version_string, git_sha):
    return (
        "// AUTO-GENERATED by scripts/gen_version.py — DO NOT EDIT BY HAND.\n"
        "// Regenerated on every PlatformIO build (pre: extra_scripts).\n"
        "#pragma once\n"
        "\n"
        "#define FW_VERSION_MAJOR  {major}\n"
        "#define FW_VERSION_MINOR  {minor}\n"
        "#define FW_VERSION_PATCH  {patch}\n"
        "#define FW_VERSION_BUILD  {build}\n"
        "#define FW_VERSION_STRING \"{version_string}\"\n"
        "#define FW_VERSION_GIT_SHA \"{git_sha}\"\n"
    ).format(
        major=major,
        minor=minor,
        patch=patch,
        build=build,
        version_string=version_string,
        git_sha=git_sha,
    )


def write_if_changed(path, content):
    """Write content to path only if it differs from the existing file."""
    if path.exists():
        try:
            existing = path.read_text()
        except OSError:
            existing = None
        if existing == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main():
    major, minor, patch, build, version_string, git_sha = resolve_version()
    content = render_header(major, minor, patch, build, version_string, git_sha)
    changed = write_if_changed(VERSION_HEADER, content)
    status = "wrote" if changed else "unchanged"
    print(
        "[gen_version] {status} {path} (FW_VERSION_STRING=\"{ver}\", "
        "build={build}, sha={sha})".format(
            status=status,
            path=VERSION_HEADER.relative_to(PROJECT_DIR),
            ver=version_string,
            build=build,
            sha=git_sha,
        )
    )


main()
