// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_3_png);    // assets\3.png
LV_IMG_DECLARE(ui_img_2_png);    // assets\2.png
LV_IMG_DECLARE(ui_img_1_png);    // assets\1.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
