// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void myfunc_1(lv_event_t * e)
{
	// Your code here
}

void myfunc_2(lv_event_t * e)
{
	// Your code here
}

void myfunc_3(lv_event_t * e)
{
	// Your code here
}
